#!/usr/bin/env bash

selected=$(\
           find \
               ~/projects ~/study \
               -mindepth 1 -maxdepth 1 -type d | \

           sed --regexp-extended "s/^\/home\/[^\/]+\///g" |

           fzf --border=rounded --reverse --prompt="  ➡️  " --ansi \
               --header="🚀 tmux-sessionizer" --header-first \
               --pointer="🔥" \
               --padding 1,0 --margin 0,2,1,2 \
               --color="prompt:blue,prompt:bold,border:green,border:dim" \
               --color="fg+:yellow" \
               --color="hl:underline,hl+:underline,hl:magenta,hl+:magenta" \
               --color="info:green" \
               --preview='export EXA_COLORS="di=33" && \
                          ~/.local/bin/exa -1 --icons --git -T -L 3 \
                          --group-directories-first -l --no-permissions --git-ignore\
                          --no-user --no-filesize --changed --no-time {} ;\
                          ' \
               --preview-window=border-left,55%)

if [ $? != 0 ]
then
    exit
fi

selected="$HOME${selected}"

selected_name=$(basename "$selected" | tr . _)

if ! tmux has-session -t $selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected nvim $selected
    tmux new-window -t $selected_name:2 -d -c $selected zsh
fi

tmux switch-client -t $selected_name
